import { Geist, Geist_Mono, Poppins, Sora, Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'], // bisa disesuaikan
  variable: '--font-poppins', // untuk pakai sebagai CSS variable
})

const sora = Sora({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // kamu bisa pilih sesuai kebutuhan
  variable: '--font-sora', // opsional: buat CSS variable
})

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-rubik',
})

export const metadata = {
  title: "Web Profil | Pashamn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className=""
    suppressHydrationWarning>
      <body
        className={sora.variable}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
